### ISSUE TITLE
Update Agbot secure-API documentation using go-swagger

### ISSUE THREAD

**Issue by codejaeger** [open-horizon/anax#2529]
Currently, the documentation for the api path `/deploycheck` is generated using `Swag` which satisfies the requirement for the different handlers for its endpoints. All such endpoints like `/deploycheck/deploycompatible` only accept a single Http method (`GET`) which is why Swag probably suffices. 
A better option seems `go-swagger` which provides much more flexibility to generate swagger specification from [code](https://goswagger.io/use/spec.html). This will be useful for the endpoint handler function [secrets](https://github.com/open-horizon/anax/blob/121b05a11bdcfa1ce39746c7be3da32a17b20fa5/agreementbot/secure_api.go#L544) which is used for multiple endpoints and Http methods for which Swag does not work. Any thoughts @dabooz @linggao ?

**Comment by codejaeger** [comment]
Hey @linggao , `go-swagger` specifications require the request body parameter description to be either in the yaml format for example
```yaml
 parameters:
 - name: checkAll
   in: query
   description: Return the compatibility check result for all the service versions referenced in the business policy or pattern.
   required: false
   type: bool
 - name: long
   in: query
   description: Show the input which was used to come up with the result.
   required: false
   type: bool
...
```

The problem is it gets too big when there are many request parameters which doesn't look good. There is an alternative to this to link the parameter from the struct definition itself like the following:

```go
// swagger:route GET /route routeID
// ...


// In the file the struct definition is placed
// swagger:parameters routeID
type routeRequest struct {
// Description
routeParam string `json:"param,omitempty"`
}
```
This seems more a flexible way but it requires making modifications outside of the `secure_api.go` for example where the deployment policy check struct is defined under `compcheck`. Does this seem a reasonable approach to you?
