### ISSUE TITLE
Feature Request: Support anax-in-container agent for Rancher Desktop as the container engine on Macos

### ISSUE THREAD

**Issue by dlarson04** [open-horizon/anax#3973]
### Is your feature request related to a problem? Please describe.

Currently anax-in-container agent fails to register when it starts on MacOS using Rancher Desktop as the container engine 

The horizon-container script tries to mount this file into the container with this argument
```
-v /private/etc/default/horizon:/etc/default/horizon:ro
```
but when using Rancher Desktop, inside the container `/etc/default/horizon` is turned into a directory so the agent doesn't have the proper environment variables set. (Same thing for agent-install.crt inside the container) 
Mounting this file with Docker on MacOS or Linux mounts this as a file inside the container.

**Comment by LiilyZhang** [comment]
Solution:
Create or update this file `~/Library/Application\ Support/rancher-desktop/lima/_config/override.yaml` with content:
```
mountType: 9p
mounts:
  - location: /private/var/tmp
    writable: true
    9p:
      securityModel: mapped-xattr
      cache: "mmap"
  - location: /private/etc/default
    writable: true
  - location: /private/etc/horizon
    writable: true
```
Also in rancher desktop -> Preferences -> Virtual Machine -> Volumes tab, change to use `9p` as Mount Type. Then restart rancher desktop
